import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import { ReactQueryProvider } from "@/providers/reactQueryProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" className="black">
        <body className={`${inter.className} bg-black text-white`}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster richColors />
        </body>
      </html>
    </SessionProvider>
  );
}
